### ISSUE TITLE
Update Storm chart to helm v3

### ISSUE THREAD

**Issue by stackedsax** [G-Research/charts#2]
When adding the LibreNMS chart, we noticed that helm v3 changes the zookeeper requirement from ~1.3.0 to 1.3.1 in requirements.yaml.  It looks like we should repackage the storm chart to update it for helm v3.

As an aside, it looks like there is an errant 1.0.1 tgz inside the 1.0.2 tgz.  We should remove that while we update the chart.

**Comment by generalfuzz** [comment]
e8963ba fixes that
