### ISSUE TITLE
Unable to install storm using version 1.0.6

### ISSUE THREAD

**Issue by bikkumala** [G-Research/charts#28]
Getting the following error while trying to install
```
Error: failed to download "gresearch/storm" (hint: running `helm repo update` may help)
```

Noticed the value url for storm version 1.0.6 is storm-1.0.6.tgz [here](https://github.com/G-Research/charts/blob/master/index.yaml#L162)

src file is present in storm folder, so value should be `storm/storm-1.0.6.tgz`

**Comment by jgiannuzzi** [comment]
Hi @bikkumala, thanks a lot for spotting this!

We will fix it ASAP 😅

**Comment by stackedsax** [comment]
@bikkumala eek!  thanks for pointing this out!
